### ISSUE TITLE
Data plotted along the reach length is clustered a the outlet of the channel

### ISSUE THREAD

**Issue by Castronova** [CUAHSI/SWOT-Data-Viewer#35]
When plotting WSE along the length of the channel, the data points appear to be clustered around the reach outlet. This doesn't appear to be correct and I believe this is because we're using the incorrect KaRin variable for the x-axis. Currently SWOT Viz is using `node_dist`, which is the "Mean distance between the observed node locations and the node locations in the PRD." Instead we should be using `p_dist_out` on the x-axis: "Along-stream distance from the reach center to the outlet, from the PRD."

When doing so, our plots transform from this:

![image](https://github.com/CUAHSI/SWOT-Data-Viewer/assets/4822372/85c9c97d-75b7-4c27-af58-a3c22ed19f7f)

to this:

![image](https://github.com/CUAHSI/SWOT-Data-Viewer/assets/4822372/4fd52393-6c2f-490d-a207-a69019621e94)

Moreover, this can be converted into length along the channel by making the x-axis relative to channel length instead of distance to outlet:

![image](https://github.com/CUAHSI/SWOT-Data-Viewer/assets/4822372/78529c1a-5038-47e2-99d8-7f9fa2d03cdc)

**Comment by devincowan** [comment]
resolved
